# Generated by Django 5.1.7 on 2025-11-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=100)),
            ],
        ),
    ]
