# Generated by Django 5.1.7 on 2025-11-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metier", "0002_voiture"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiture",
            name="couleur",
            field=models.CharField(default="", max_length=10),
        ),
    ]
